IntakeApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace IntakeApp.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

IntakeApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntakeApp.Classes;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Globalization;

namespace IntakeApp.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;

		[BindProperty]
		public string Product { get; set; }
		public List<SelectListItem> Ddl_Products { get; } = new List<SelectListItem> { };

		Dal dal = new Dal();

		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		[BindProperty]
		public string Category { get; set; }
		public List<SelectListItem> Ddl_Category { get; } = new List<SelectListItem> { };

		[BindProperty]
		public string Status { get; set; }
		public List<SelectListItem> Ddl_Status { get; } = new List<SelectListItem> { };

		[BindProperty]
		public new string User { get; set; }
		public List<SelectListItem> Ddl_User { get; } = new List<SelectListItem> { };


		public void OnGet()
		{
			//Populatie Productdropdownlist
			List<Product> products = dal.GetProducts();
			foreach (Product product in products)
			{
				Ddl_Products.Add(new SelectListItem { Value = product.getProductId().ToString(), Text = product.getName() });
			}
			List<Category> Categories = dal.GetCategorys();
			foreach (Category Category in Categories)
			{
				Ddl_Category.Add(new SelectListItem { Value = Category.GetCategoryId().ToString(), Text = Category.GetCategoryName() });
			}
			List<Status> Statusses = dal.GetStatus();
			foreach (Status Status in Statusses)
			{
				Ddl_Status.Add(new SelectListItem { Value = Status.GetStatusId().ToString(), Text = Status.GetStatusName() });
			}
			List<User> Users = dal.GetUser();
			foreach (User User in Users)
			{
				Ddl_User.Add(new SelectListItem { Value = User.GetId().ToString(), Text = User.GetFirst() });
			}
		}
		public void OnPostInput()
		{
			var articleCommentary = Request.Form["articleCommentary"];
			//var articleImage = Request.Form["fileupload"];

			
            //maak object van class op basis van invoerveld, doe vervolgens code uit dal daarmee

            DateTime dateOne = DateTime.ParseExact("06/04/2021 10:00", "MM/dd/yyyy HH:mm", CultureInfo.InvariantCulture);
            DateTime dateTwo = DateTime.ParseExact("06/04/2021 10:00", "MM/dd/yyyy HH:mm", CultureInfo.InvariantCulture);

            int chosenProduct = Convert.ToInt32(Product);
            int chosenUser = Convert.ToInt32(User);
			System.Diagnostics.Debug.WriteLine(chosenUser);

			Article newArtcile = new Article(0, chosenProduct, 1, chosenUser, 0, dateOne, dateTwo, "leeg", articleCommentary);
            dal.AddNewArticle(newArtcile);

            //Het onderdeel dat bij het aanmaken van een nieuw artikel de punten bijschrijft bij de gebruiker.Via de ingevoerde categorie zoekt hij
            //de bijbehorende punten. Hierna wordt de gebruiker gezocht op basis van de keuze. De punten uit de categorie worden bij deze gebruiker
            //bijgeschreven. 



            Category fromCategory = dal.GetCategoryByProduct(chosenProduct);
            int rewardedPoints = fromCategory.GetPoints();

            //Zoekt het userId op en voegt de punten toe bij de functie in de DAL.Het opzoeken van de user doet hij ook automatisch in deze
            //functie.

            int userId = chosenUser;
            dal.AddPointsToUser(userId, rewardedPoints);
            OnGet();
        }

		public void OnPostAddProduct()
		{
			//maak object van class op basis van invoerveld, doe vervolgens code uit dal daarmee
			
			int chosenCategory = Convert.ToInt32(Category);
			var productName = Request.Form["productName"];
			var productDescription = Request.Form["productDescription"];

			Product newProduct = new Product(0, chosenCategory, productName, productDescription);
			System.Diagnostics.Debug.WriteLine(chosenCategory);
			dal.AddNewProduct(newProduct);
			OnGet();
		}
	}
}

IntakeApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IntakeApp.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

IntakeApp/Pages/Index.cshtml
@page
@model IndexModel
@{
	ViewData["Title"] = "Home page";
}

@*<div class="text-center">
		<h1 class="display-4">Welcome</h1>
		<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
	</div>*@


<title>Intake producten.</title>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
	<script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
	<script type="text/javascript">
        function ShowImagePreview(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#<%=ImgPrv.ClientID%>').prop('src', e.target.result)
                        .width(240)
                        .height(150);
                };
                reader.readAsDataURL(input.files[0]);
                }
            }
	</script>
</head>
<body>
	<style type="text/css">
		.auto-style2 {
			width: 254px;
			font-family: Arial, Helvetica, sans-serif;
		}

		.auto-style3 {
			width: 255px;
			font-family: Arial, Helvetica, sans-serif;
		}

		.auto-style12 {
			height: 26px;
		}

		.auto-style14 {
			width: 216px;
			height: 26px;
			font-family: Arial, Helvetica, sans-serif;
		}

		.auto-style15 {
			font-family: Arial, Helvetica, sans-serif;
		}

		.auto-style16 {
			width: 216px;
			font-family: Arial, Helvetica, sans-serif;
		}

		.auto-style17 {
			width: 100%;
		}

		.auto-style18 {
			width: 1551px;
			height: 170px;
		}

		.auto-style19 {
			height: 1080px;
			margin-left: 0px;
		}

		.auto-style20 {
			margin-left: 1360px;
			width: 191px;
			height: 94px;
		}

		.auto-style21 {
			width: 36%;
			position: absolute;
			left: -88px;
			top: 142px;
			font-family: Arial, Helvetica, sans-serif;
			margin-left: 1188px;
		}

		.auto-style22 {
			width: 255px;
			font-family: Arial, Helvetica, sans-serif;
			height: 26px;
		}

		.auto-style25 {
			width: 254px;
			font-family: Arial, Helvetica, sans-serif;
			height: 26px;
		}

		.auto-style26 {
			width: 504px;
		}

		.auto-style27 {
			width: 2265px;
		}

		.auto-style28 {
			width: 249px;
		}

		.auto-style29 {
			margin-left: 1360px;
			width: 191px;
			height: 51px;
		}

		.auto-style30 {
			width: 223px;
		}
	</style>
	<form asp-controller="Notes" asp-action="Index" method="get" id="form1" runat="server"/>
</body>

</html>
<div class="auto-style19">
    <p class="site-title">
        <a href="@Url.Action("Index", "Home")">
            <img src="../Images/Ruiolwinkel Vaals Logo.png"/>
        </a>
    </p>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>
    </head>
    <body>
        <form asp-controller="Home">
            <input id="fileupload" name="fileupload" type="file" />
            <hr />
            <div id="dvPreview"></div>
        </form>
        <script type="text/javascript">
            $(function () {
                $("#fileupload").change(function () {
                    $("#dvPreview").html("");
                    var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
                    if (regex.test($(this).val().toLowerCase())) {
                        if (typeof (FileReader) != "undefined") {
                            $("#dvPreview").show();
                            $("#dvPreview").append("<img />");
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                $("#dvPreview img").attr("src", e.target.result);
                                $("#dvPreview img").attr("style", "height:200px;width: 200px");
                            }
                            reader.readAsDataURL($(this)[0].files[0]);
                        } else {
                            alert("This browser does not support FileReader.");
                        }
                    } else {
                        alert("Please upload a valid image file.");
                    }
                });
            });
        </script>
    </body>
</html>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span class="auto-style15">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; User
        
    </span>

<br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<!-- het uitkiezen voor welke user het toegevoegd moet worden -->
@*</asp:DropDownList>*@
	&nbsp;<br />
<br />
    <form method="post">
<table style="width:100%;" class="auto-style15">
    <tr>
        <td class="auto-style3">&nbsp;</td>
        <td class="auto-style16">Gebruiker </td>
        <td>
            @Html.DropDownListFor(x => Model.User, new SelectList(Model.Ddl_User, "Value", "Text"), new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td class="auto-style3">&nbsp;</td>
        <td class="auto-style16">Product </td>
        <td>
            @Html.DropDownListFor(x => Model.Product, new SelectList(Model.Ddl_Products, "Value", "Text"), new { @class = "form-control" })
        </td>
    </tr>
    
</table>
<table class="auto-style17">
    
    <tr>
        <td class="auto-style25"></td>
        <td class="auto-style14">Commentary </td>
        <td class="auto-style12"> <input id="commentary" name="articleCommentary" runat="server" type="text" class="auto-style15" /></td>
    </tr>
</table>
<p class="auto-style29">
    <br />
    &nbsp;<button asp-page-handler="Input" ID="btnAddProduct" runat="server" onclick="OnPostInput" CssClass="auto-style15">Add Product</button>
</p>
<table class="auto-style15" style="width:100%;">
    <tr>
        <td class="auto-style28">&nbsp;</td>
        <td class="auto-style30">Product name</td>
        <td>
            <input id="productName" name="productName" runat="server" type="text" />
        </td>
    </tr>
    <tr>
        <td class="auto-style28">&nbsp;</td>
        <td class="auto-style30">Category</td>
        <td>
            @Html.DropDownListFor(x => Model.Category, new SelectList(Model.Ddl_Category, "Value", "Text"), new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td class="auto-style28">&nbsp;</td>
        <td class="auto-style30">Product Description</td>
        <td>
            <input id="productDescription" name="productDescription" runat="server" type="text" />
        </td>
    </tr>
</table>
<div id="addNewProduct" class="auto-style18" draggable="true">
    <p class="auto-style20">
        <br />
        &nbsp;<button asp-page-handler="AddProduct" ID="btnAddNewProduct" runat="server" onclick="OnPostAddProduct" CssClass="auto-style15">Add New Product</button>
       
    </p>
   
</div>
        </form>
</div>

IntakeApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntakeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">IntakeApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IntakeApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>